"""
SentinelFlow AI — SQLAlchemy ORM Models
Complete schema covering Users, Incidents, Audit Trails, Telemetry, Timelines,
Prompt Templates, and Observability Traces.
"""

from datetime import datetime, timezone
from sqlalchemy import (
    Column, Integer, String, Float, DateTime, ForeignKey,
    Text, Boolean, Index, Enum as SAEnum,
)
from sqlalchemy.orm import relationship
from sqlalchemy.types import TypeDecorator

from ..core.database import Base
from ..core.security import encrypt_text, decrypt_text


# ── Custom Encrypted Column Type ─────────────────────────────
class EncryptedText(TypeDecorator):
    """Transparent AES-256 encryption/decryption for sensitive columns."""
    impl = Text
    cache_ok = True

    def process_bind_param(self, value, dialect):
        if value is not None:
            return encrypt_text(value)
        return value

    def process_result_value(self, value, dialect):
        if value is not None:
            return decrypt_text(value)
        return value


def _utcnow():
    return datetime.now(timezone.utc)


# ── User Model ───────────────────────────────────────────────
class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    email = Column(String(255), unique=True, index=True, nullable=False)
    hashed_password = Column(String(255), nullable=False)
    full_name = Column(String(255), default="")
    role = Column(String(50), default="engineer")  # admin, engineer, viewer
    organization_id = Column(String(50), nullable=True)
    email_verified = Column(Boolean, default=False)
    email_verified_at = Column(DateTime, nullable=True)
    password_reset_token = Column(String(255), nullable=True)
    password_reset_expires = Column(DateTime, nullable=True)
    mfa_backup_codes = Column(EncryptedText, nullable=True)  # Comma-separated backup codes
    last_login = Column(DateTime, nullable=True)
    login_count = Column(Integer, default=0)
    is_active = Column(Boolean, default=True)
    mfa_enabled = Column(Boolean, default=False)
    mfa_secret = Column(EncryptedText, nullable=True)
    created_at = Column(DateTime, default=_utcnow)
    updated_at = Column(DateTime, default=_utcnow, onupdate=_utcnow)

    # Relationships
    sessions = relationship("UserSession", back_populates="user", cascade="all, delete-orphan")


# ── User Session Model ───────────────────────────────────────
class UserSession(Base):
    __tablename__ = "user_sessions"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    refresh_token = Column(String(512), unique=True, index=True, nullable=False)
    ip_address = Column(String(45), nullable=True)
    user_agent = Column(String(255), nullable=True)
    is_revoked = Column(Boolean, default=False)
    expires_at = Column(DateTime, nullable=False)
    created_at = Column(DateTime, default=_utcnow)

    user = relationship("User", back_populates="sessions")


# ── Incident Model ──────────────────────────────────────────
class Incident(Base):
    __tablename__ = "incidents"

    id = Column(Integer, primary_key=True, index=True)
    correlation_id = Column(String(64), unique=True, index=True, nullable=False)
    source = Column(String(100), nullable=False)          # "K8s Telemetry Monitor"
    metric_type = Column(String(50), nullable=False)       # "CPU_SPIKE", "UNAUTHORIZED_ACCESS"
    severity = Column(String(20), nullable=False)          # "CRITICAL", "WARNING", "INFO"
    title = Column(String(500), nullable=False)
    description = Column(EncryptedText, nullable=False)
    status = Column(String(30), default="DETECTED")
    alert_count = Column(Integer, default=1)
    confidence_score = Column(Float, default=0.0)
    suggested_action = Column(Text, nullable=True)
    assigned_to = Column(String(255), nullable=True)
    parent_incident_id = Column(Integer, ForeignKey("incidents.id", ondelete="SET NULL"), nullable=True)
    resolved_at = Column(DateTime, nullable=True)
    root_cause_json = Column(Text, nullable=True)  # Structured RCA JSON payload
    executive_report_json = Column(Text, nullable=True)  # Caching for C-suite summaries
    k8s_analysis_json = Column(Text, nullable=True)  # Kubernetes specific analysis JSON
    explainability_json = Column(Text, nullable=True)  # AI Explainability payload JSON
    priority_score = Column(Integer, default=0)  # Dynamic priority score (0-100)
    sla_target = Column(String(50), nullable=True)  # "P0", "P1", "P2", "P3", "P4"
    sla_breach_at = Column(DateTime, nullable=True)  # Predicted SLA breach timestamp
    simulation_json = Column(Text, nullable=True)  # Simulated "what-if" impact JSON
    remediation_options_json = Column(Text, nullable=True)  # Ranked options generated by RemediationAgent
    decision_graph_json = Column(Text, nullable=True)  # Direct Acyclic Graph structure of AI decisions
    recommended_runbooks_json = Column(Text, nullable=True)  # Ranked runbooks list
    attack_graph_json = Column(Text, nullable=True)  # Direct attack flow lateral movement representation JSON
    created_at = Column(DateTime, default=_utcnow, index=True)
    updated_at = Column(DateTime, default=_utcnow, onupdate=_utcnow)

    # Relationships
    logs = relationship("IncidentLog", back_populates="incident", cascade="all, delete-orphan")
    audit_trails = relationship("AuditTrail", back_populates="incident")
    timeline_events = relationship("TimelineEvent", back_populates="incident", cascade="all, delete-orphan")
    feedbacks = relationship("RecommendationFeedback", back_populates="incident", cascade="all, delete-orphan")
    replay_events = relationship("ReplayEvent", back_populates="incident", cascade="all, delete-orphan")
    fingerprints = relationship("AlertFingerprint", back_populates="incident", cascade="all, delete-orphan")
    
    parent_incident = relationship("Incident", remote_side="[Incident.id]", backref="cascading_incidents")

    __table_args__ = (
        Index("ix_incidents_status_severity", "status", "severity"),
    )


# ── Incident Log ────────────────────────────────────────────
class IncidentLog(Base):
    __tablename__ = "incident_logs"

    id = Column(Integer, primary_key=True, index=True)
    incident_id = Column(Integer, ForeignKey("incidents.id", ondelete="CASCADE"), nullable=False)
    stage = Column(String(50), nullable=False)
    # Stages: DETECTION, RAG_RETRIEVAL, PROMPT_LOAD, REASONING, CONTRADICTION_CHECK,
    #         SAFETY_CHECK, CONFIDENCE_GATE, HITL_WAIT, EXECUTION, RESOLUTION
    message = Column(EncryptedText, nullable=False)
    metadata_json = Column(Text, nullable=True)  # JSON blob for extra context
    timestamp = Column(DateTime, default=_utcnow)

    incident = relationship("Incident", back_populates="logs")


# ── Timeline Event ──────────────────────────────────────────
class TimelineEvent(Base):
    __tablename__ = "timeline_events"

    id = Column(Integer, primary_key=True, index=True)
    incident_id = Column(Integer, ForeignKey("incidents.id", ondelete="CASCADE"), nullable=False)
    event_type = Column(String(50), nullable=False)
    # Types: DETECTED, ANALYZED, RAG_MATCH, LLM_REASONING, SAFETY_CHECK_PASS,
    #        SAFETY_CHECK_FAIL, HITL_REQUESTED, HITL_APPROVED, HITL_REJECTED,
    #        EXECUTION_START, EXECUTION_COMPLETE, RESOLUTION
    title = Column(String(500), nullable=False)
    description = Column(Text, nullable=True)
    actor = Column(String(100), default="system")  # "system", "agent", user email
    decision_rationale = Column(Text, nullable=True)  # Explainability capture
    confidence_at_step = Column(Float, nullable=True)
    duration_ms = Column(Float, nullable=True)
    mitre_technique = Column(String(50), nullable=True)     # e.g., T1059.001
    source_system = Column(String(100), nullable=True)       # e.g., Auditd, Syslog, K8s
    event_severity = Column(String(20), nullable=True)       # e.g., CRITICAL, HIGH, MEDIUM, LOW
    parent_event_id = Column(Integer, ForeignKey("timeline_events.id", ondelete="SET NULL"), nullable=True)
    timestamp = Column(DateTime, default=_utcnow, index=True)

    incident = relationship("Incident", back_populates="timeline_events")
    parent_event = relationship("TimelineEvent", remote_side=[id])


# ── Audit Trail ─────────────────────────────────────────────
class AuditTrail(Base):
    __tablename__ = "audit_trails"

    id = Column(Integer, primary_key=True, index=True)
    incident_id = Column(Integer, ForeignKey("incidents.id"), nullable=True)
    command_checked = Column(EncryptedText, nullable=False)
    status = Column(String(20), nullable=False)  # "ALLOWED", "BLOCKED"
    risk_score = Column(Float, default=0.0)
    risk_assessment = Column(Text, nullable=True)
    remediation_action = Column(String(255), nullable=True)
    performed_by = Column(String(255), default="SentinelFlow AI Agent")
    hash = Column(String(64), nullable=True)
    prev_hash = Column(String(64), nullable=True)
    timestamp = Column(DateTime, default=_utcnow, index=True)

    incident = relationship("Incident", back_populates="audit_trails")


# ── Metric Sample ───────────────────────────────────────────
class MetricSample(Base):
    __tablename__ = "metric_samples"

    id = Column(Integer, primary_key=True, index=True)
    node_name = Column(String(100), default="node-01")
    pod_name = Column(String(100), nullable=True)
    namespace = Column(String(100), default="default")
    cpu_usage = Column(Float, default=0.0)
    memory_usage = Column(Float, default=0.0)
    disk_usage = Column(Float, default=0.0)
    network_rx_bytes = Column(Float, default=0.0)
    network_tx_bytes = Column(Float, default=0.0)
    requests_per_sec = Column(Float, default=0.0)
    latency_ms = Column(Float, default=0.0)
    error_rate = Column(Float, default=0.0)
    timestamp = Column(DateTime, default=_utcnow, index=True)


# ── Prompt Template (CRISPE Framework) ──────────────────────
class PromptTemplate(Base):
    __tablename__ = "prompt_templates"

    id = Column(String(50), primary_key=True, index=True)
    name = Column(String(200), nullable=False)
    capacity = Column(Text, nullable=False)
    role = Column(Text, nullable=False)
    intent = Column(Text, nullable=False)
    subject = Column(Text, nullable=False)
    premium_response = Column(Text, nullable=False)
    evaluation = Column(Text, nullable=False)
    category = Column(String(50), default="general")
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=_utcnow)
    updated_at = Column(DateTime, default=_utcnow, onupdate=_utcnow)


# ── AI Observability Trace ──────────────────────────────────
class AIObservabilityTrace(Base):
    __tablename__ = "ai_observability_traces"

    id = Column(Integer, primary_key=True, index=True)
    correlation_id = Column(String(64), index=True, nullable=False)
    step_name = Column(String(50), nullable=False)
    # Steps: INGEST, ANOMALY_DETECTION, CRISPE_PROMPT_LOAD, QDRANT_RAG_RETRIEVAL,
    #        LLM_REASONING, MASTRA_CONTRADICTION_CHECK, ENKRYPT_SAFETY_CHECK,
    #        CONFIDENCE_GATE, EXECUTION, NOTIFICATION
    input_tokens = Column(Integer, default=0)
    output_tokens = Column(Integer, default=0)
    latency_ms = Column(Float, default=0.0)
    status = Column(String(20), default="success")  # success, error, skipped
    error_message = Column(Text, nullable=True)
    metadata_json = Column(Text, nullable=True)
    timestamp = Column(DateTime, default=_utcnow, index=True)


# ── Feature Flag ────────────────────────────────────────────
class FeatureFlag(Base):
    __tablename__ = "feature_flags"

    id = Column(Integer, primary_key=True, index=True)
    key = Column(String(100), unique=True, nullable=False)
    value = Column(Boolean, default=False)
    description = Column(Text, nullable=True)
    updated_by = Column(String(255), nullable=True)
    updated_at = Column(DateTime, default=_utcnow, onupdate=_utcnow)


# ── Notification Log ────────────────────────────────────────
class NotificationLog(Base):
    __tablename__ = "notification_logs"

    id = Column(Integer, primary_key=True, index=True)
    incident_id = Column(Integer, ForeignKey("incidents.id"), nullable=True)
    channel = Column(String(50), nullable=False)  # "slack", "webhook", "email"
    recipient = Column(String(255), nullable=True)
    message = Column(Text, nullable=False)
    status = Column(String(20), default="sent")  # "sent", "delivered", "failed"
    response_action = Column(String(50), nullable=True)  # "approved", "rejected"
    timestamp = Column(DateTime, default=_utcnow)


# ── Role Model (RBAC) ────────────────────────────────────────
class Role(Base):
    __tablename__ = "roles"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(50), unique=True, index=True, nullable=False)
    description = Column(String(255), nullable=True)


# ── Permission Model (RBAC) ──────────────────────────────────
class Permission(Base):
    __tablename__ = "permissions"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), unique=True, index=True, nullable=False)
    description = Column(String(255), nullable=True)


# ── Role-Permission Link Table (RBAC) ────────────────────────
class RolePermission(Base):
    __tablename__ = "role_permissions"

    id = Column(Integer, primary_key=True, index=True)
    role_id = Column(Integer, ForeignKey("roles.id", ondelete="CASCADE"), nullable=False)
    permission_id = Column(Integer, ForeignKey("permissions.id", ondelete="CASCADE"), nullable=False)


# ── Security Policy Model ────────────────────────────────────
class SecurityPolicy(Base):
    __tablename__ = "security_policies"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), unique=True, nullable=False)
    strictness = Column(String(20), default="high")  # low, medium, high
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=_utcnow)
    updated_at = Column(DateTime, default=_utcnow, onupdate=_utcnow)


# ── Policy Rule Model ────────────────────────────────────────
class PolicyRule(Base):
    __tablename__ = "policy_rules"

    id = Column(Integer, primary_key=True, index=True)
    policy_id = Column(Integer, ForeignKey("security_policies.id", ondelete="CASCADE"), nullable=False)
    pattern = Column(String(255), nullable=False)  # e.g., "rm -rf"
    rule_type = Column(String(50), default="DENYLIST")  # DENYLIST, ALLOWLIST
    risk_weight = Column(Float, default=1.0)
    created_at = Column(DateTime, default=_utcnow)


# ── Mastra Workflow State Persistence ────────────────────────
class MastraWorkflowState(Base):
    __tablename__ = "mastra_workflow_states"

    id = Column(Integer, primary_key=True, index=True)
    workflow_name = Column(String(100), nullable=False)
    correlation_id = Column(String(64), unique=True, index=True, nullable=False)
    current_state = Column(String(50), nullable=False)
    context_data_json = Column(Text, nullable=True)
    is_completed = Column(Boolean, default=False)
    created_at = Column(DateTime, default=_utcnow)
    updated_at = Column(DateTime, default=_utcnow, onupdate=_utcnow)


# ── Mastra Workflow Step Metrics ─────────────────────────────
class MastraWorkflowStep(Base):
    __tablename__ = "mastra_workflow_steps"

    id = Column(Integer, primary_key=True, index=True)
    workflow_state_id = Column(Integer, ForeignKey("mastra_workflow_states.id", ondelete="CASCADE"), nullable=False)
    step_name = Column(String(100), nullable=False)
    status = Column(String(20), default="pending")  # pending, running, completed, failed
    started_at = Column(DateTime, default=_utcnow)
    ended_at = Column(DateTime, nullable=True)
    error_message = Column(Text, nullable=True)


# ── Qdrant Collection Metadata ───────────────────────────────
class QdrantCollectionMetadata(Base):
    __tablename__ = "qdrant_collection_metadata"

    id = Column(Integer, primary_key=True, index=True)
    collection_name = Column(String(100), unique=True, nullable=False)
    vector_dimension = Column(Integer, default=384)
    distance_metric = Column(String(20), default="Cosine")
    created_at = Column(DateTime, default=_utcnow)


# ── RAG Runbook Memory Metadata ──────────────────────────────
class RAGRunbookMemory(Base):
    __tablename__ = "rag_runbook_memories"

    id = Column(Integer, primary_key=True, index=True)
    runbook_title = Column(String(200), nullable=False)
    content_summary = Column(Text, nullable=False)
    vector_payload_id = Column(String(64), nullable=True)  # Point ID in Qdrant
    created_at = Column(DateTime, default=_utcnow)


# ── Cloud Provider Config Model ──────────────────────────────
class CloudProviderConfig(Base):
    __tablename__ = "cloud_provider_configs"

    id = Column(Integer, primary_key=True, index=True)
    provider_name = Column(String(50), nullable=False)  # AWS, GCP, Azure, Mock
    credentials_mask = Column(String(100), default="********")
    region = Column(String(50), default="us-east-1")
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=_utcnow)


# ── Kubernetes Cluster Info Model ────────────────────────────
class KubernetesClusterInfo(Base):
    __tablename__ = "kubernetes_cluster_infos"

    id = Column(Integer, primary_key=True, index=True)
    cluster_name = Column(String(100), unique=True, nullable=False)
    api_endpoint = Column(String(255), nullable=False)
    namespaces_list = Column(Text, default="default,production,kube-system")
    status = Column(String(20), default="connected")
    created_at = Column(DateTime, default=_utcnow)


# ── Remediation Execution Output ──────────────────────────────
class RemediationExecution(Base):
    __tablename__ = "remediation_executions"

    id = Column(Integer, primary_key=True, index=True)
    incident_id = Column(Integer, ForeignKey("incidents.id", ondelete="CASCADE"), nullable=False)
    command = Column(EncryptedText, nullable=False)
    execution_status = Column(String(20), default="PENDING")  # PENDING, SUCCESS, FAILED
    console_output = Column(Text, nullable=True)
    executed_by = Column(String(255), nullable=True)
    started_at = Column(DateTime, default=_utcnow)
    finished_at = Column(DateTime, nullable=True)


# ── Incident Comment Model ────────────────────────────────────
class IncidentComment(Base):
    __tablename__ = "incident_comments"

    id = Column(Integer, primary_key=True, index=True)
    incident_id = Column(Integer, ForeignKey("incidents.id", ondelete="CASCADE"), nullable=False)
    author = Column(String(255), nullable=False)
    content = Column(Text, nullable=False)
    created_at = Column(DateTime, default=_utcnow)


# ── Threat Intelligence Cache Model ───────────────────────────
class ThreatIntelEnrichment(Base):
    __tablename__ = "threat_intel_enrichments"

    id = Column(Integer, primary_key=True, index=True)
    ioc_type = Column(String(30), nullable=False, index=True)      # ip, domain, hash, url, email
    ioc_value = Column(String(255), nullable=False, index=True)
    source = Column(String(100), nullable=False)                    # VirusTotal, AbuseIPDB, etc.
    threat_level = Column(String(20), nullable=False, default="CLEAN")  # HIGH, MEDIUM, LOW, CLEAN
    context = Column(Text, nullable=True)                           # Serialized JSON metadata
    created_at = Column(DateTime, default=_utcnow)
    updated_at = Column(DateTime, default=_utcnow, onupdate=_utcnow)


# ── Recommendation Feedback Model ────────────────────────────
class RecommendationFeedback(Base):
    __tablename__ = "recommendation_feedbacks"

    id = Column(Integer, primary_key=True, index=True)
    incident_id = Column(Integer, ForeignKey("incidents.id", ondelete="CASCADE"), nullable=False)
    original_recommendation = Column(Text, nullable=False)
    engineer_correction = Column(Text, nullable=False)
    reasoning = Column(Text, nullable=True)
    created_at = Column(DateTime, default=_utcnow, index=True)

    incident = relationship("Incident", back_populates="feedbacks")


# ── Incident Replay Event Model ────────────────────────────────
class ReplayEvent(Base):
    __tablename__ = "replay_events"

    id = Column(Integer, primary_key=True, index=True)
    incident_id = Column(Integer, ForeignKey("incidents.id", ondelete="CASCADE"), nullable=False, index=True)
    event_timestamp = Column(DateTime, default=_utcnow, index=True)
    event_type = Column(String(50), nullable=False)
    event_data = Column(Text, nullable=True)  # JSON payload representation
    agent_name = Column(String(100), nullable=True)
    decision = Column(String(200), nullable=True)
    reasoning = Column(Text, nullable=True)

    incident = relationship("Incident", back_populates="replay_events")


# ── Knowledge Base Document Model ────────────────────────────
class KnowledgeDocument(Base):
    __tablename__ = "knowledge_documents"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String(255), nullable=False)
    filename = Column(String(255), nullable=False)
    category = Column(String(50), nullable=False, index=True)      # runbooks, sops, playbooks, guides
    subcategory = Column(String(50), nullable=True)                 # kubernetes, aws, security, performance
    tags = Column(String(255), nullable=True)                       # comma-separated values
    version = Column(String(20), nullable=False, default="1.0.0")
    author = Column(String(100), nullable=False)
    content = Column(Text, nullable=False)                          # Extracted text content for RAG embedding search
    status = Column(String(30), nullable=False, default="draft")    # draft, approved, archived
    approved_by = Column(String(100), nullable=True)
    approved_at = Column(DateTime, nullable=True)
    usage_count = Column(Integer, default=0)
    success_count = Column(Integer, default=0)
    created_at = Column(DateTime, default=_utcnow, index=True)
    updated_at = Column(DateTime, default=_utcnow, onupdate=_utcnow)


# ── Governance Execution Config Model ──────────────────────────
class ExecutionConfig(Base):
    __tablename__ = "execution_configs"

    id = Column(Integer, primary_key=True, index=True)
    mode = Column(String(50), nullable=False, default="MANUAL")           # MANUAL, SEMI_AUTONOMOUS, FULLY_AUTONOMOUS
    rate_limit_per_minute = Column(Integer, nullable=False, default=5)
    min_confidence_score = Column(Integer, nullable=False, default=90)
    max_blast_radius = Column(Integer, nullable=False, default=10)
    restricted_services = Column(String(255), nullable=True, default="payment") # comma-separated
    low_risk_actions = Column(String(255), nullable=True, default="restart_pod,scale_service,rollout_restart") # comma-separated
    updated_at = Column(DateTime, default=_utcnow, onupdate=_utcnow)

# ── Alert Fingerprinting Models ────────────────────────────────
class AlertFingerprint(Base):
    __tablename__ = "alert_fingerprints"

    id = Column(Integer, primary_key=True, index=True)
    incident_id = Column(Integer, ForeignKey("incidents.id", ondelete="SET NULL"), nullable=True)
    fingerprint_hash = Column(String(64), unique=True, index=True, nullable=False)
    first_alert = Column(DateTime, default=_utcnow)
    last_alert_time = Column(DateTime, default=_utcnow, onupdate=_utcnow)
    alert_count = Column(Integer, default=1)

    # Relationships
    alerts = relationship("Alert", back_populates="fingerprint")
    incident = relationship("Incident", back_populates="fingerprints")


class Alert(Base):
    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, index=True)
    fingerprint_id = Column(Integer, ForeignKey("alert_fingerprints.id", ondelete="CASCADE"), nullable=True)
    source = Column(String(100), nullable=False)
    alert_type = Column(String(50), nullable=False)
    service = Column(String(100), nullable=False)
    message = Column(Text, nullable=False)
    timestamp = Column(DateTime, default=_utcnow)

    # Relationships
    fingerprint = relationship("AlertFingerprint", back_populates="alerts")


class IdempotencyKey(Base):
    __tablename__ = "idempotency_keys"

    key = Column(String(255), primary_key=True, unique=True, index=True)
    incident_id = Column(Integer, nullable=True)
    action_type = Column(String(100), nullable=True)
    response_json = Column(Text, nullable=True)  # Stored as {"status_code": int, "body": dict}
    created_at = Column(DateTime, default=_utcnow)
    expires_at = Column(DateTime, nullable=False, index=True)


class Policy(Base):
    __tablename__ = "policies"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(255), nullable=False)
    description = Column(String(512), nullable=True)
    enabled = Column(Boolean, default=True)
    conditions_json = Column(Text, nullable=False) # JSON condition criteria
    actions_json = Column(Text, nullable=False)    # JSON string array of action names
    exceptions_json = Column(Text, nullable=True)  # JSON array of exempted service names
    rate_limit = Column(Integer, default=10)
    approval_required = Column(Boolean, default=False)
    created_at = Column(DateTime, default=_utcnow)


