"""add playbook execution persistence

Revision ID: 481649a6726e
Revises: 921df3bafd69
Create Date: 2026-07-25 12:23:44.802268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '481649a6726e'
down_revision: Union[str, None] = '921df3bafd69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playbook_executions',
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('playbook_name', sa.String(length=255), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('progress_pct', sa.Float(), nullable=True),
    sa.Column('steps_json', sa.JSON(), nullable=False),
    sa.Column('log_json', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_completion', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_index(op.f('ix_playbook_executions_execution_id'), 'playbook_executions', ['execution_id'], unique=False)
    op.create_index(op.f('ix_playbook_executions_incident_id'), 'playbook_executions', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playbook_executions_incident_id'), table_name='playbook_executions')
    op.drop_index(op.f('ix_playbook_executions_execution_id'), table_name='playbook_executions')
    op.drop_table('playbook_executions')
    # ### end Alembic commands ###

