"""add_learning_and_executive

Revision ID: 50057a3eb811
Revises: 1f5bed033aa1
Create Date: 2026-07-08 11:59:12.046320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50057a3eb811'
down_revision: Union[str, None] = '1f5bed033aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_intel_enrichments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ioc_type', sa.String(length=30), nullable=False),
    sa.Column('ioc_value', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('threat_level', sa.String(length=20), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_intel_enrichments_id'), 'threat_intel_enrichments', ['id'], unique=False)
    op.create_index(op.f('ix_threat_intel_enrichments_ioc_type'), 'threat_intel_enrichments', ['ioc_type'], unique=False)
    op.create_index(op.f('ix_threat_intel_enrichments_ioc_value'), 'threat_intel_enrichments', ['ioc_value'], unique=False)
    op.create_table('recommendation_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('original_recommendation', sa.Text(), nullable=False),
    sa.Column('engineer_correction', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_feedbacks_created_at'), 'recommendation_feedbacks', ['created_at'], unique=False)
    op.create_index(op.f('ix_recommendation_feedbacks_id'), 'recommendation_feedbacks', ['id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(length=512), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_refresh_token'), 'user_sessions', ['refresh_token'], unique=True)
    
    with op.batch_alter_table('incidents') as batch_op:
        batch_op.add_column(sa.Column('root_cause_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('executive_report_json', sa.Text(), nullable=True))
        
    with op.batch_alter_table('timeline_events') as batch_op:
        batch_op.add_column(sa.Column('mitre_technique', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('source_system', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('event_severity', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('parent_event_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_timeline_events_parent', 'timeline_events', ['parent_event_id'], ['id'], ondelete='SET NULL')
        
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('password_reset_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('password_reset_expires', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('mfa_backup_codes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('login_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_column('login_count')
        batch_op.drop_column('last_login')
        batch_op.drop_column('mfa_backup_codes')
        batch_op.drop_column('password_reset_expires')
        batch_op.drop_column('password_reset_token')
        batch_op.drop_column('email_verified_at')
        batch_op.drop_column('email_verified')
        batch_op.drop_column('organization_id')
        
    with op.batch_alter_table('timeline_events') as batch_op:
        batch_op.drop_constraint('fk_timeline_events_parent', type_='foreignkey')
        batch_op.drop_column('parent_event_id')
        batch_op.drop_column('event_severity')
        batch_op.drop_column('source_system')
        batch_op.drop_column('mitre_technique')
        
    with op.batch_alter_table('incidents') as batch_op:
        batch_op.drop_column('executive_report_json')
        batch_op.drop_column('root_cause_json')
        
    op.drop_index(op.f('ix_user_sessions_refresh_token'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_recommendation_feedbacks_id'), table_name='recommendation_feedbacks')
    op.drop_index(op.f('ix_recommendation_feedbacks_created_at'), table_name='recommendation_feedbacks')
    op.drop_table('recommendation_feedbacks')
    op.drop_index(op.f('ix_threat_intel_enrichments_ioc_value'), table_name='threat_intel_enrichments')
    op.drop_index(op.f('ix_threat_intel_enrichments_ioc_type'), table_name='threat_intel_enrichments')
    op.drop_index(op.f('ix_threat_intel_enrichments_id'), table_name='threat_intel_enrichments')
    op.drop_table('threat_intel_enrichments')
    # ### end Alembic commands ###
