"""add_replay_and_enrichments_columns

Revision ID: 56ad6cfaf4a2
Revises: c9d8319d0079
Create Date: 2026-07-08 13:13:14.998304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56ad6cfaf4a2'
down_revision: Union[str, None] = 'c9d8319d0079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replay_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_data', sa.Text(), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('decision', sa.String(length=200), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replay_events_event_timestamp'), 'replay_events', ['event_timestamp'], unique=False)
    op.create_index(op.f('ix_replay_events_id'), 'replay_events', ['id'], unique=False)
    op.create_index(op.f('ix_replay_events_incident_id'), 'replay_events', ['incident_id'], unique=False)
    op.add_column('incidents', sa.Column('priority_score', sa.Integer(), nullable=True))
    op.add_column('incidents', sa.Column('sla_target', sa.String(length=50), nullable=True))
    op.add_column('incidents', sa.Column('sla_breach_at', sa.DateTime(), nullable=True))
    op.add_column('incidents', sa.Column('simulation_json', sa.Text(), nullable=True))
    op.add_column('incidents', sa.Column('remediation_options_json', sa.Text(), nullable=True))
    op.add_column('incidents', sa.Column('decision_graph_json', sa.Text(), nullable=True))
    op.add_column('incidents', sa.Column('recommended_runbooks_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'recommended_runbooks_json')
    op.drop_column('incidents', 'decision_graph_json')
    op.drop_column('incidents', 'remediation_options_json')
    op.drop_column('incidents', 'simulation_json')
    op.drop_column('incidents', 'sla_breach_at')
    op.drop_column('incidents', 'sla_target')
    op.drop_column('incidents', 'priority_score')
    op.drop_index(op.f('ix_replay_events_incident_id'), table_name='replay_events')
    op.drop_index(op.f('ix_replay_events_id'), table_name='replay_events')
    op.drop_index(op.f('ix_replay_events_event_timestamp'), table_name='replay_events')
    op.drop_table('replay_events')
    # ### end Alembic commands ###
