"""add_k8s_analysis

Revision ID: 5ee5fca1975f
Revises: 50057a3eb811
Create Date: 2026-07-08 12:21:59.367899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ee5fca1975f'
down_revision: Union[str, None] = '50057a3eb811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('k8s_analysis_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'k8s_analysis_json')
    # ### end Alembic commands ###
