"""add is_simulated and simulation_reason to incidents

Revision ID: 7278e0684a6b
Revises: 481649a6726e
Create Date: 2026-07-25 18:31:25.253117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7278e0684a6b'
down_revision: Union[str, None] = '481649a6726e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('is_simulated', sa.Boolean(), nullable=True))
    op.add_column('incidents', sa.Column('simulation_reason', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'simulation_reason')
    op.drop_column('incidents', 'is_simulated')
    # ### end Alembic commands ###

