"""add_attack_graph_column

Revision ID: 85fb60863392
Revises: 14acfafcc03d
Create Date: 2026-07-08 13:48:35.277697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85fb60863392'
down_revision: Union[str, None] = '14acfafcc03d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('attack_graph_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'attack_graph_json')
    # ### end Alembic commands ###
