"""add_execution_configs_table

Revision ID: 921df3bafd69
Revises: 85fb60863392
Create Date: 2026-07-08 13:57:08.695662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '921df3bafd69'
down_revision: Union[str, None] = '85fb60863392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('min_confidence_score', sa.Integer(), nullable=False),
    sa.Column('max_blast_radius', sa.Integer(), nullable=False),
    sa.Column('restricted_services', sa.String(length=255), nullable=True),
    sa.Column('low_risk_actions', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_configs_id'), 'execution_configs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_configs_id'), table_name='execution_configs')
    op.drop_table('execution_configs')
    # ### end Alembic commands ###
