"""add_explainability_column

Revision ID: c9d8319d0079
Revises: 5ee5fca1975f
Create Date: 2026-07-08 12:29:30.145011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9d8319d0079'
down_revision: Union[str, None] = '5ee5fca1975f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('explainability_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'explainability_json')
    # ### end Alembic commands ###
