"""Add extended schema tables

Revision ID: e9102f429f1e
Revises: b37fdb6f607b
Create Date: 2026-07-06 17:40:11.622117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.models


# revision identifiers, used by Alembic.
revision: str = 'e9102f429f1e'
down_revision: Union[str, None] = 'b37fdb6f607b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_provider_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('credentials_mask', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_provider_configs_id'), 'cloud_provider_configs', ['id'], unique=False)
    op.create_table('kubernetes_cluster_infos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_name', sa.String(length=100), nullable=False),
    sa.Column('api_endpoint', sa.String(length=255), nullable=False),
    sa.Column('namespaces_list', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_name')
    )
    op.create_index(op.f('ix_kubernetes_cluster_infos_id'), 'kubernetes_cluster_infos', ['id'], unique=False)
    op.create_table('mastra_workflow_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_name', sa.String(length=100), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('current_state', sa.String(length=50), nullable=False),
    sa.Column('context_data_json', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mastra_workflow_states_correlation_id'), 'mastra_workflow_states', ['correlation_id'], unique=True)
    op.create_index(op.f('ix_mastra_workflow_states_id'), 'mastra_workflow_states', ['id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('qdrant_collection_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_name', sa.String(length=100), nullable=False),
    sa.Column('vector_dimension', sa.Integer(), nullable=True),
    sa.Column('distance_metric', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_name')
    )
    op.create_index(op.f('ix_qdrant_collection_metadata_id'), 'qdrant_collection_metadata', ['id'], unique=False)
    op.create_table('rag_runbook_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('runbook_title', sa.String(length=200), nullable=False),
    sa.Column('content_summary', sa.Text(), nullable=False),
    sa.Column('vector_payload_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_runbook_memories_id'), 'rag_runbook_memories', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('security_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('strictness', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_security_policies_id'), 'security_policies', ['id'], unique=False)
    op.create_table('mastra_workflow_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_state_id', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_state_id'], ['mastra_workflow_states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mastra_workflow_steps_id'), 'mastra_workflow_steps', ['id'], unique=False)
    op.create_table('policy_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=True),
    sa.Column('risk_weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['security_policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_rules_id'), 'policy_rules', ['id'], unique=False)
    op.create_table('remediation_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('command', app.models.models.EncryptedText(), nullable=False),
    sa.Column('execution_status', sa.String(length=20), nullable=True),
    sa.Column('console_output', sa.Text(), nullable=True),
    sa.Column('executed_by', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediation_executions_id'), 'remediation_executions', ['id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_permissions_id'), 'role_permissions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_permissions_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_remediation_executions_id'), table_name='remediation_executions')
    op.drop_table('remediation_executions')
    op.drop_index(op.f('ix_policy_rules_id'), table_name='policy_rules')
    op.drop_table('policy_rules')
    op.drop_index(op.f('ix_mastra_workflow_steps_id'), table_name='mastra_workflow_steps')
    op.drop_table('mastra_workflow_steps')
    op.drop_index(op.f('ix_security_policies_id'), table_name='security_policies')
    op.drop_table('security_policies')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_rag_runbook_memories_id'), table_name='rag_runbook_memories')
    op.drop_table('rag_runbook_memories')
    op.drop_index(op.f('ix_qdrant_collection_metadata_id'), table_name='qdrant_collection_metadata')
    op.drop_table('qdrant_collection_metadata')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_mastra_workflow_states_id'), table_name='mastra_workflow_states')
    op.drop_index(op.f('ix_mastra_workflow_states_correlation_id'), table_name='mastra_workflow_states')
    op.drop_table('mastra_workflow_states')
    op.drop_index(op.f('ix_kubernetes_cluster_infos_id'), table_name='kubernetes_cluster_infos')
    op.drop_table('kubernetes_cluster_infos')
    op.drop_index(op.f('ix_cloud_provider_configs_id'), table_name='cloud_provider_configs')
    op.drop_table('cloud_provider_configs')
    # ### end Alembic commands ###
