"""
SentinelFlow AI — Observability Stack
Integrates OpenTelemetry tracing, Prometheus client metrics, and structured structlog logging.
"""

import os
import sys
import logging
from typing import Any, Dict, Optional
import structlog
from prometheus_client import Counter, Histogram, CollectorRegistry, Gauge
from opentelemetry import trace
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor, ConsoleSpanExporter
from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor
from .config import get_settings

settings = get_settings()

# ── 1. Structured Logging Setup ──────────────────────────────

def add_otel_trace_info(_, __, event_dict: Dict[str, Any]) -> Dict[str, Any]:
    """Processor to inject OpenTelemetry trace and span context into logs."""
    current_span = trace.get_current_span()
    if current_span and current_span.get_span_context().is_valid:
        context = current_span.get_span_context()
        event_dict["trace_id"] = f"{context.trace_id:032x}"
        event_dict["span_id"] = f"{context.span_id:16x}"
    return event_dict


def setup_structured_logging():
    """Configure structlog for standard production JSON or dev console logging."""
    processors = [
        structlog.contextvars.merge_contextvars,
        structlog.processors.add_log_level,
        structlog.processors.TimeStamper(fmt="iso"),
        add_otel_trace_info,
        structlog.processors.StackInfoRenderer(),
        structlog.processors.format_exc_info,
    ]

    if settings.ENVIRONMENT == "production":
        # Production JSON format
        processors.append(structlog.processors.JSONRenderer())
    else:
        # Development clean color format
        processors.append(structlog.dev.ConsoleRenderer(colors=True))

    structlog.configure(
        processors=processors,
        logger_factory=structlog.PrintLoggerFactory(),
        cache_logger_on_first_use=True,
    )

# Run logging setup on import
setup_structured_logging()
logger = structlog.get_logger("sentinelflow")


# ── 2. OpenTelemetry Tracing Setup ────────────────────────────

tracer = None
if settings.OTEL_ENABLED:
    try:
        # Initialize SDK tracing provider
        provider = TracerProvider()
        
        # Default console exporter (production would use OTLPSpanExporter to OTEL collector)
        processor = BatchSpanProcessor(ConsoleSpanExporter())
        provider.add_span_processor(processor)
        trace.set_tracer_provider(provider)
        
        tracer = trace.get_tracer("sentinelflow-tracer")
        logger.info("OpenTelemetry Tracing initialized successfully.")
    except Exception as e:
        logger.error("Failed to initialize OpenTelemetry Tracing:", error=str(e))
else:
    # Fake Tracer/NullTracer fallback
    tracer = trace.get_tracer(__name__)
    logger.info("OpenTelemetry Tracing disabled. Falling back to local tracing context.")


# ── 3. Prometheus Custom Metrics Registry ─────────────────────

# Single shared collector registry
METRIC_REGISTRY = CollectorRegistry()

# Incident Tracking
SF_INCIDENTS_TOTAL = Counter(
    "sf_incidents_total",
    "Total count of ingested and created incidents",
    ["severity", "status", "metric_type"],
    registry=METRIC_REGISTRY
)

# Workflow Engine Performance
SF_WORKFLOW_STEP_LATENCY_SECONDS = Histogram(
    "sf_workflow_step_latency_seconds",
    "Latencies of individual incident response steps in seconds",
    ["step_name", "status"],
    buckets=(0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0),
    registry=METRIC_REGISTRY
)

# LLM Operations Tracking
SF_LLM_CALLS_TOTAL = Counter(
    "sf_llm_calls_total",
    "Total count of LLM provider execution requests",
    ["provider", "status"],
    registry=METRIC_REGISTRY
)

SF_LLM_DURATION_SECONDS = Histogram(
    "sf_llm_duration_seconds",
    "Latencies of LLM execution requests in seconds",
    ["provider"],
    buckets=(0.5, 1.0, 2.0, 5.0, 10.0, 20.0),
    registry=METRIC_REGISTRY
)

# HTTP Service Health Tracking
SF_ERROR_RATE_TOTAL = Counter(
    "sf_error_rate_total",
    "Total error responses generated by the service gateway API",
    ["path", "status_code"],
    registry=METRIC_REGISTRY
)

# WebSocket Metrics
SF_WS_CONNECTIONS_ACTIVE = Gauge(
    "sf_ws_connections_active",
    "Total active concurrent WebSocket connections",
    registry=METRIC_REGISTRY
)

SF_WS_MESSAGES_DELIVERED_TOTAL = Counter(
    "sf_ws_messages_delivered_total",
    "Total messages delivered over WebSockets",
    ["status"],
    registry=METRIC_REGISTRY
)

def track_ws_connection(change: int):
    try:
        if change > 0:
            SF_WS_CONNECTIONS_ACTIVE.inc(change)
        else:
            SF_WS_CONNECTIONS_ACTIVE.dec(abs(change))
    except Exception as e:
        logger.warning("Metrics track WS connection failed:", error=str(e))

def track_ws_message_delivery(status: str):
    try:
        SF_WS_MESSAGES_DELIVERED_TOTAL.labels(status=status).inc()
    except Exception as e:
        logger.warning("Metrics track WS delivery failed:", error=str(e))


# Helper metric logging utilities
def track_incident_created(severity: str, status: str, metric_type: str):
    try:
        SF_INCIDENTS_TOTAL.labels(severity=severity, status=status, metric_type=metric_type).inc()
    except Exception as e:
        logger.warning("Metrics track incident failed:", error=str(e))


def track_workflow_step(step_name: str, status: str, duration_sec: float):
    try:
        SF_WORKFLOW_STEP_LATENCY_SECONDS.labels(step_name=step_name, status=status).observe(duration_sec)
    except Exception as e:
        logger.warning("Metrics track workflow failed:", error=str(e))


def track_llm_request(provider: str, status: str, duration_sec: float):
    try:
        SF_LLM_CALLS_TOTAL.labels(provider=provider, status=status).inc()
        SF_LLM_DURATION_SECONDS.labels(provider=provider).observe(duration_sec)
    except Exception as e:
        logger.warning("Metrics track LLM failed:", error=str(e))


# ── 4. FastAPI Instrumentation Hook ───────────────────────────

def instrument_app(app):
    """Integrate FastAPI instrumentation hooks for OTel and endpoints mapping."""
    if settings.OTEL_ENABLED:
        try:
            FastAPIInstrumentor.instrument_app(app)
            logger.info("FastAPI application OTel instrumentation applied.")
        except Exception as e:
            logger.error("FastAPI OTel instrumentation failed:", error=str(e))
